name: msu_helper
description: Handy MSU utilities

dependencies:
  android_intent: any
  url_launcher: any
  intl: any
  sqflite: any
  path_provider: any
  path: any
  events: any
  json_annotation: ^0.2.3
  http: any
  shared_preferences: any
  synchronized: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^0.5.0
  #flutter_launch_icons: any


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
  assets:
    - assets/dining/msu_beef.png
    - assets/dining/msu_pork.png
    - assets/dining/vegan.png
    - assets/dining/vegetarian.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#8BC34A"
  adaptive_icon_foreground: "assets/foreground.png"
